/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : CAMPO.c
**     Project   : Project2_24_05
**     Processor : MC9S12C128CFU16
**     Component : BitsIO
**     Version   : Component 02.102, Driver 03.14, CPU db: 2.87.410
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 24/05/2018, 15:45
**     Abstract  :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
**     Settings  :
**         Port name                   : B
**
**         Bit mask of the port        : $00F0
**         Number of bits/pins         : 4
**         Single bit numbers          : 0 to 3
**         Values range                : 0 to 15
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 15 = 00FH
**         Initial pull option         : up
**
**         Port data register          : PORTB     [$0001]
**         Port control register       : DDRB      [$0003]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    20   |   PB4_ADDR4_DATA4
**                    1      |    21   |   PB5_ADDR5_DATA5
**                    2      |    22   |   PB6_ADDR6_DATA6
**                    3      |    23   |   PB7_ADDR7_DATA7
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents  :
**         GetDir - bool CAMPO_GetDir(void);
**         GetVal - byte CAMPO_GetVal(void);
**         PutVal - void CAMPO_PutVal(byte Val);
**         GetBit - bool CAMPO_GetBit(byte Bit);
**         PutBit - void CAMPO_PutBit(byte Bit, bool Val);
**         SetBit - void CAMPO_SetBit(byte Bit);
**         ClrBit - void CAMPO_ClrBit(byte Bit);
**         NegBit - void CAMPO_NegBit(byte Bit);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE CAMPO. */

#include "CAMPO.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG CAMPO_DATA            /* Select data segment "CAMPO_DATA" */
#pragma CODE_SEG CAMPO_CODE
#pragma CONST_SEG CAMPO_CONST          /* Constant section for this module */
/*
** ===================================================================
**     Method      :  CAMPO_GetMsk (component BitsIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const byte CAMPO_Table[4U] = {  /* Table of mask constants */
   0x10U, 0x20U, 0x40U, 0x80U
};

static byte CAMPO_GetMsk (byte PinIndex)
{
  return (byte)((PinIndex<4U) ? CAMPO_Table[PinIndex] : 0U); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  CAMPO_GetVal (component BitsIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 15)
** ===================================================================
*/
byte CAMPO_GetVal(void)
{
  return (byte)((getReg8(PORTB) & 0xF0U) >> 4U); /* Return port data */
}

/*
** ===================================================================
**     Method      :  CAMPO_PutVal (component BitsIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 15)
**     Returns     : Nothing
** ===================================================================
*/
void CAMPO_PutVal(byte Val)
{
  Val = (byte)((Val & 0x0FU) << 4U);   /* Mask and shift output value */
  setReg8(PORTB, (getReg8(PORTB) & (byte)(~(byte)0xF0U)) | Val); /* Put masked value on port */
}

/*
** ===================================================================
**     Method      :  CAMPO_GetBit (component BitsIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 3)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool CAMPO_GetBit(byte Bit)
{
  byte const Mask = CAMPO_GetMsk(Bit); /* Temporary variable - bit mask to test */
  return (bool)(((getReg8(PORTB) & Mask) == Mask)? 1U: 0U); /* Test if specified bit of port register is set */
}

/*
** ===================================================================
**     Method      :  CAMPO_PutBit (component BitsIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 3)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void CAMPO_PutBit(byte Bit, bool Val)
{
  byte const Mask = CAMPO_GetMsk(Bit); /* Temporary variable - put bit mask */
  if (Val) {
    setReg8Bits(PORTB, Mask);          /* [bit (Bit+4)]=0x01U */
  } else { /* !Val */
    clrReg8Bits(PORTB, Mask);          /* [bit (Bit+4)]=0x00U */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  CAMPO_ClrBit (component BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
void CAMPO_ClrBit(byte Bit)
{
  byte const Mask = CAMPO_GetMsk(Bit); /* Temporary variable - set bit mask */
  clrReg8Bits(PORTB, Mask);            /* [bit (Bit+4)]=0x00U */
}

/*
** ===================================================================
**     Method      :  CAMPO_SetBit (component BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 3)
**     Returns     : Nothing
** ===================================================================
*/
void CAMPO_SetBit(byte Bit)
{
  byte const Mask = CAMPO_GetMsk(Bit); /* Temporary variable - set bit mask */
  setReg8Bits(PORTB, Mask);            /* [bit (Bit+4)]=0x01U */
}

/*
** ===================================================================
**     Method      :  CAMPO_NegBit (component BitsIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void CAMPO_NegBit(byte Bit)
{
  byte const Mask = CAMPO_GetMsk(Bit); /* Temporary variable - set bit mask */
  invertReg8Bits(PORTB, Mask);         /* [bit (Bit+4)]=invert */
}

/*
** ===================================================================
**     Method      :  CAMPO_GetDir (component BitsIO)
**
**     Description :
**         This method returns direction of the component.
**     Parameters  : None
**     Returns     :
**         ---        - Direction of the component (always TRUE, Output only)
**                      FALSE = Input, TRUE = Output
** ===================================================================
*/
/*
bool CAMPO_GetDir(void)

**  This method is implemented as a macro. See CAMPO.h file.  **
*/


/* END CAMPO. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
