/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : LEDON.c
**     Project   : Project2_24_05
**     Processor : MC9S12C128CFU16
**     Component : TimerInt
**     Version   : Component 02.159, Driver 01.20, CPU db: 2.87.410
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 24/05/2018, 17:06
**     Abstract  :
**         This component "TimerInt" implements a periodic interrupt.
**         When the component and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings  :
**         Timer name                  : TIM_Counter (16-bit)
**         Compare name                : TC1
**         Counter shared              : Yes
**
**         High speed mode
**             Prescaler               : divide-by-8
**             Clock                   : 250000 Hz
**           Initial period/frequency
**             Xtal ticks              : 1000000
**             microseconds            : 250000
**             milliseconds            : 250
**             seconds (real)          : 0.25
**             Hz                      : 4
**
**         Runtime setting             : none
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : TCNT      [$0044]
**              Mode                   : TIOS      [$0040]
**              Run                    : TSCR1     [$0046]
**              Prescaler              : TSCR2     [$004D]
**
**         Compare registers
**              Compare                : TC1       [$0052]
**
**         Flip-flop registers
**              Mode                   : TCTL2     [$0049]
**     Contents  :
**         Enable - byte LEDON_Enable(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE LEDON. */

#include "Events.h"
#include "LEDON.h"

#pragma DATA_SEG LEDON_DATA            /* Select data segment "LEDON_DATA" */
#pragma CODE_SEG LEDON_CODE
#pragma CONST_SEG DEFAULT              /* Use default segment for constants */



/* Internal method prototypes */


/* End of Internal methods declarations */

/*
** ===================================================================
**     Method      :  LEDON_Enable (component TimerInt)
**
**     Description :
**         This method enables the component - it starts the timer.
**         Events may be generated (<DisableEvent>/<EnableEvent>).
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte LEDON_Enable(void)
{
  /* This method is useless, because component is enabled in initialization and has no Disable method */ 
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  LEDON_Interrupt (component TimerInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(LEDON_Interrupt)
{
  TC1 += 0xF424U;                      /* Add value corresponding with period */
  TFLG1 = 0x02U;                       /* Reset interrupt request flag */
  LEDON_OnInterrupt();                 /* Invoke user event */
}

#pragma CODE_SEG LEDON_CODE

/* END LEDON. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
